file '../dist/ruby.wasm' do
  system('bundle exec rbwasm build -o ../dist/ruby.wasm')
end

task :build => ['../dist/ruby.wasm'] do
  system('bundle exec rbwasm pack ../dist/ruby.wasm --dir ./src::/src -o ../dist/app.wasm')
end
